Run lint in workflow
vexflow/vexflow pull request #197
Opened 2024-03-20 17:08 UTC by J43fura

resolves #192

2024-03-20 20:49 UTC, ronyeh approved these changes

2024-03-20 20:51 UTC, ronyeh requested changes
Should it be:
```
npm run lint
```

npm lint causes the workflow to fail.

2024-03-21 23:47 UTC, ronyeh approved these changes

2024-03-21 23:49 UTC, merged

2024-03-21 23:50 UTC, ronyeh commented
Thanks @J43fura!

2024-03-22 10:26 UTC, J43fura commented
It was my pleasure @ronyeh